+ NGPUS=4
+ PORT=19889
+ PY_ARGS='--config ./cfgs/ShapeNet55_models/PoinTr_amlp.yaml --save_dir s3://NLP/jsy/checkpoints/pointr_experiments --exp_name amlp_in1536_out3072 --resume'
+ python -m torch.distributed.launch --master_port=19889 --nproc_per_node=4 main.py --launcher pytorch --sync_bn --config ./cfgs/ShapeNet55_models/PoinTr_amlp.yaml --save_dir s3://NLP/jsy/checkpoints/pointr_experiments --exp_name amlp_in1536_out3072 --resume
/mnt/cache/jiangshuyang/.conda/envs/pointr/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "main.py", line 1, in <module>
Traceback (most recent call last):
  File "main.py", line 1, in <module>
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from tools import run_net
  File "/mnt/cache/jiangshuyang/PoinTr/tools/__init__.py", line 1, in <module>
    from tools import run_net
  File "/mnt/cache/jiangshuyang/PoinTr/tools/__init__.py", line 1, in <module>
    from tools import run_net
  File "/mnt/cache/jiangshuyang/PoinTr/tools/__init__.py", line 1, in <module>
    from tools import run_net
  File "/mnt/cache/jiangshuyang/PoinTr/tools/__init__.py", line 1, in <module>
    from .runner import run_net
  File "/mnt/cache/jiangshuyang/PoinTr/tools/runner.py", line 5, in <module>
    from .runner import run_net
  File "/mnt/cache/jiangshuyang/PoinTr/tools/runner.py", line 5, in <module>
    from .runner import run_net
  File "/mnt/cache/jiangshuyang/PoinTr/tools/runner.py", line 5, in <module>
    from .runner import run_net
  File "/mnt/cache/jiangshuyang/PoinTr/tools/runner.py", line 5, in <module>
    from tools import builder
  File "/mnt/cache/jiangshuyang/PoinTr/tools/builder.py", line 8, in <module>
    from tools import builder
  File "/mnt/cache/jiangshuyang/PoinTr/tools/builder.py", line 8, in <module>
    from tools import builder
  File "/mnt/cache/jiangshuyang/PoinTr/tools/builder.py", line 8, in <module>
    from tools import builder
  File "/mnt/cache/jiangshuyang/PoinTr/tools/builder.py", line 8, in <module>
    from models import build_model_from_cfg
  File "/mnt/cache/jiangshuyang/PoinTr/models/__init__.py", line 3, in <module>
    from models import build_model_from_cfg
  File "/mnt/cache/jiangshuyang/PoinTr/models/__init__.py", line 3, in <module>
    from models import build_model_from_cfg
  File "/mnt/cache/jiangshuyang/PoinTr/models/__init__.py", line 3, in <module>
    from models import build_model_from_cfg
  File "/mnt/cache/jiangshuyang/PoinTr/models/__init__.py", line 3, in <module>
    import models.PoinTr
  File "/mnt/cache/jiangshuyang/PoinTr/models/PoinTr.py", line 8, in <module>
    import models.PoinTr
  File "/mnt/cache/jiangshuyang/PoinTr/models/PoinTr.py", line 8, in <module>
    import models.PoinTr
  File "/mnt/cache/jiangshuyang/PoinTr/models/PoinTr.py", line 8, in <module>
    import models.PoinTr
  File "/mnt/cache/jiangshuyang/PoinTr/models/PoinTr.py", line 8, in <module>
    from .Transformer import PCTransformer
          File "/mnt/cache/jiangshuyang/PoinTr/models/Transformer.py", line 10, in <module>
from .Transformer import PCTransformerfrom .Transformer import PCTransformer

  File "/mnt/cache/jiangshuyang/PoinTr/models/Transformer.py", line 10, in <module>
  File "/mnt/cache/jiangshuyang/PoinTr/models/Transformer.py", line 10, in <module>
    from .Transformer import PCTransformer
  File "/mnt/cache/jiangshuyang/PoinTr/models/Transformer.py", line 10, in <module>
    from efficient_attention import AMLP, ABC, AMLPSeq
      File "/mnt/cache/jiangshuyang/efficient-attention/efficient_attention/__init__.py", line 93, in <module>
from efficient_attention import AMLP, ABC, AMLPSeq
  File "/mnt/cache/jiangshuyang/efficient-attention/efficient_attention/__init__.py", line 93, in <module>
    from efficient_attention import AMLP, ABC, AMLPSeq
  File "/mnt/cache/jiangshuyang/efficient-attention/efficient_attention/__init__.py", line 93, in <module>
    from efficient_attention import AMLP, ABC, AMLPSeq
  File "/mnt/cache/jiangshuyang/efficient-attention/efficient_attention/__init__.py", line 93, in <module>
    from .s4d import S4D
      File "/mnt/cache/jiangshuyang/efficient-attention/efficient_attention/s4d.py", line 9, in <module>
    from .s4d import S4Dfrom .s4d import S4D

  File "/mnt/cache/jiangshuyang/efficient-attention/efficient_attention/s4d.py", line 9, in <module>
  File "/mnt/cache/jiangshuyang/efficient-attention/efficient_attention/s4d.py", line 9, in <module>
    from .s4d import S4D
  File "/mnt/cache/jiangshuyang/efficient-attention/efficient_attention/s4d.py", line 9, in <module>
    import opt_einsum as oe
    import opt_einsum as oe
ModuleNotFoundError: No module named 'opt_einsum'
ModuleNotFoundError: No module named 'opt_einsum'
    import opt_einsum as oe
ModuleNotFoundError: No module named 'opt_einsum'
    import opt_einsum as oe
ModuleNotFoundError: No module named 'opt_einsum'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 80653) of binary: /mnt/cache/jiangshuyang/.conda/envs/pointr/bin/python
Traceback (most recent call last):
  File "/mnt/cache/jiangshuyang/.conda/envs/pointr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/mnt/cache/jiangshuyang/.conda/envs/pointr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/cache/jiangshuyang/.conda/envs/pointr/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/mnt/cache/jiangshuyang/.conda/envs/pointr/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/mnt/cache/jiangshuyang/.conda/envs/pointr/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/mnt/cache/jiangshuyang/.conda/envs/pointr/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/mnt/cache/jiangshuyang/.conda/envs/pointr/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/cache/jiangshuyang/.conda/envs/pointr/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-07-14_11:06:59
  host      : SH-IDC1-10-140-1-71
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 80654)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2022-07-14_11:06:59
  host      : SH-IDC1-10-140-1-71
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 80655)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2022-07-14_11:06:59
  host      : SH-IDC1-10-140-1-71
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 80656)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-07-14_11:06:59
  host      : SH-IDC1-10-140-1-71
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 80653)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: SH-IDC1-10-140-1-71: task 0: Exited with exit code 1
